"""create faucet tables

Revision ID: 04873c4a8d8f
Revises: 
Create Date: 2026-09-30 11:15:15.251467
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '04873c4a8d8f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chain_id', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('nonce', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("wallet_address ~ '^0x[0-9a-f]{40}$'", name='challenge_wallet_normalized_evm_address'),
    sa.CheckConstraint('chain_id BETWEEN 1 AND 115792089237316195423570985008687907853269984665640564039457584007913129639935', name='challenge_chain_id_uint256'),
    sa.CheckConstraint('expires_at > created_at', name='challenge_expiry_after_creation'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nonce')
    )
    op.create_table('claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chain_id', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('challenge_id', sa.Uuid(), nullable=False),
    sa.Column('amount_wei', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('reserved_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.String(length=80), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.CheckConstraint("(status = 'confirmed') = (confirmed_at IS NOT NULL)", name='claim_confirmation_state_consistent'),
    sa.CheckConstraint("(status = 'failed') = (failed_at IS NOT NULL)", name='claim_failure_state_consistent'),
    sa.CheckConstraint("status IN ('reserved', 'submitted', 'broadcast_unknown', 'confirmed', 'failed')", name='claim_status_valid'),
    sa.CheckConstraint("wallet_address ~ '^0x[0-9a-f]{40}$'", name='claim_wallet_normalized_evm_address'),
    sa.CheckConstraint('amount_wei BETWEEN 1 AND 115792089237316195423570985008687907853269984665640564039457584007913129639935', name='claim_amount_uint256'),
    sa.CheckConstraint('chain_id BETWEEN 1 AND 115792089237316195423570985008687907853269984665640564039457584007913129639935', name='claim_chain_id_uint256'),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id'),
    sa.UniqueConstraint('id', 'chain_id', name='claim_id_chain_unique')
    )
    op.create_index('claims_latest_confirmation_per_wallet', 'claims', ['chain_id', 'wallet_address', sa.literal_column('confirmed_at DESC')], unique=False, postgresql_where=sa.text("status = 'confirmed'"))
    op.create_index('claims_one_active_per_wallet', 'claims', ['chain_id', 'wallet_address'], unique=True, postgresql_where=sa.text("status IN ('reserved', 'submitted', 'broadcast_unknown')"))
    op.create_table('transaction_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('chain_id', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('sender_address', sa.String(length=42), nullable=False),
    sa.Column('sender_nonce', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('transaction_hash', sa.String(length=66), nullable=False),
    sa.Column('signed_raw_transaction', sa.LargeBinary(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('broadcast_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('receipt_block_number', sa.Numeric(precision=78, scale=0), nullable=True),
    sa.Column('receipt_block_hash', sa.String(length=66), nullable=True),
    sa.Column('failure_code', sa.String(length=80), nullable=True),
    sa.CheckConstraint("receipt_block_hash IS NULL OR receipt_block_hash ~ '^0x[0-9a-f]{64}$'", name='attempt_receipt_hash_normalized_bytes32'),
    sa.CheckConstraint("sender_address ~ '^0x[0-9a-f]{40}$'", name='attempt_sender_normalized_evm_address'),
    sa.CheckConstraint("status IN ('prepared', 'broadcast_unknown', 'submitted', 'confirmed', 'reverted', 'replaced')", name='attempt_status_valid'),
    sa.CheckConstraint("transaction_hash ~ '^0x[0-9a-f]{64}$'", name='attempt_hash_normalized_bytes32'),
    sa.CheckConstraint('chain_id BETWEEN 1 AND 115792089237316195423570985008687907853269984665640564039457584007913129639935', name='attempt_chain_id_uint256'),
    sa.CheckConstraint('sender_nonce BETWEEN 0 AND 115792089237316195423570985008687907853269984665640564039457584007913129639935', name='attempt_nonce_uint256'),
    sa.ForeignKeyConstraint(['claim_id', 'chain_id'], ['claims.id', 'claims.chain_id'], name='attempt_claim_chain_fk'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain_id', 'transaction_hash', name='attempt_hash_per_chain'),
    sa.UniqueConstraint('claim_id', 'attempt_number', name='attempt_number_per_claim')
    )
    op.create_index('transaction_attempts_by_claim', 'transaction_attempts', ['claim_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('transaction_attempts_by_claim', table_name='transaction_attempts')
    op.drop_table('transaction_attempts')
    op.drop_index('claims_one_active_per_wallet', table_name='claims', postgresql_where=sa.text("status IN ('reserved', 'submitted', 'broadcast_unknown')"))
    op.drop_index('claims_latest_confirmation_per_wallet', table_name='claims', postgresql_where=sa.text("status = 'confirmed'"))
    op.drop_table('claims')
    op.drop_table('challenges')
    # ### end Alembic commands ###
