"""add request rate limit events

Revision ID: 06c31c28f5e9
Revises: 4395a2b06f6a
Create Date: 2026-09-30 13:07:40.831012
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '06c31c28f5e9'
down_revision: Union[str, None] = '4395a2b06f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('identity_type', sa.String(length=16), nullable=False),
    sa.Column('identity_hash', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.CheckConstraint("action IN ('challenge', 'claim')", name='rate_limit_action_valid'),
    sa.CheckConstraint("identity_hash ~ '^[0-9a-f]{64}$'", name='rate_limit_identity_hash_sha256'),
    sa.CheckConstraint("identity_type IN ('ip', 'subnet', 'wallet')", name='rate_limit_identity_type_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('rate_limit_events_expiry', 'rate_limit_events', ['occurred_at'], unique=False)
    op.create_index('rate_limit_events_lookup', 'rate_limit_events', ['action', 'identity_type', 'identity_hash', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('rate_limit_events_lookup', table_name='rate_limit_events')
    op.drop_index('rate_limit_events_expiry', table_name='rate_limit_events')
    op.drop_table('rate_limit_events')
    # ### end Alembic commands ###
