"""add distributor nonce coordination

Revision ID: 4395a2b06f6a
Revises: 04873c4a8d8f
Create Date: 2026-09-30 12:52:24.630560
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4395a2b06f6a'
down_revision: Union[str, None] = '04873c4a8d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_attempts', sa.Column('gas_limit', sa.Numeric(precision=78, scale=0), nullable=True))
    op.add_column('transaction_attempts', sa.Column('gas_price_wei', sa.Numeric(precision=78, scale=0), nullable=True))
    op.add_column('transaction_attempts', sa.Column('max_fee_per_gas_wei', sa.Numeric(precision=78, scale=0), nullable=True))
    op.add_column('transaction_attempts', sa.Column('max_priority_fee_per_gas_wei', sa.Numeric(precision=78, scale=0), nullable=True))
    op.create_index('transaction_attempts_by_sender_nonce', 'transaction_attempts', ['chain_id', 'sender_address', 'sender_nonce'], unique=False)
    op.create_index('transaction_attempts_one_active_per_nonce', 'transaction_attempts', ['chain_id', 'sender_address', 'sender_nonce'], unique=True, postgresql_where=sa.text("status IN ('prepared', 'broadcast_unknown', 'submitted')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('transaction_attempts_one_active_per_nonce', table_name='transaction_attempts', postgresql_where=sa.text("status IN ('prepared', 'broadcast_unknown', 'submitted')"))
    op.drop_index('transaction_attempts_by_sender_nonce', table_name='transaction_attempts')
    op.drop_column('transaction_attempts', 'max_priority_fee_per_gas_wei')
    op.drop_column('transaction_attempts', 'max_fee_per_gas_wei')
    op.drop_column('transaction_attempts', 'gas_price_wei')
    op.drop_column('transaction_attempts', 'gas_limit')
    # ### end Alembic commands ###
